import type { Options } from "../../types/form"

const TIME_ZONES: Options = [
	{
		label: "Africa",
		options: [
			{
				label: "Africa/Abidjan",
				value: "Africa/Abidjan",
				name: "Côte d'Ivoire",
				alpha2: "CI",
				alpha3: "CIV",
				numeric: 384,
			},
			{
				label: "Africa/Accra",
				value: "Africa/Accra",
				name: "Ghana",
				alpha2: "GH",
				alpha3: "GHA",
				numeric: 288,
			},
			{
				label: "Africa/Addis_Ababa",
				value: "Africa/Addis_Ababa",
				name: "Ethiopia",
				alpha2: "ET",
				alpha3: "ETH",
				numeric: 231,
			},
			{
				label: "Africa/Algiers",
				value: "Africa/Algiers",
				name: "Algeria",
				alpha2: "DZ",
				alpha3: "DZA",
				numeric: 12,
			},
			{
				label: "Africa/Asmara",
				value: "Africa/Asmara",
				name: "Eritrea",
				alpha2: "ER",
				alpha3: "ERI",
				numeric: 232,
			},
			{
				label: "Africa/Bamako",
				value: "Africa/Bamako",
				name: "Mali",
				alpha2: "ML",
				alpha3: "MLI",
				numeric: 466,
			},
			{
				label: "Africa/Bangui",
				value: "Africa/Bangui",
				name: "Central African Republic (the)",
				alpha2: "CF",
				alpha3: "CAF",
				numeric: 140,
			},
			{
				label: "Africa/Banjul",
				value: "Africa/Banjul",
				name: "Gambia (the)",
				alpha2: "GM",
				alpha3: "GMB",
				numeric: 270,
			},
			{
				label: "Africa/Bissau",
				value: "Africa/Bissau",
				name: "Guinea-Bissau",
				alpha2: "GW",
				alpha3: "GNB",
				numeric: 624,
			},
			{
				label: "Africa/Blantyre",
				value: "Africa/Blantyre",
				name: "Malawi",
				alpha2: "MW",
				alpha3: "MWI",
				numeric: 454,
			},
			{
				label: "Africa/Brazzaville",
				value: "Africa/Brazzaville",
				name: "Congo (the)",
				alpha2: "CG",
				alpha3: "COG",
				numeric: 178,
			},
			{
				label: "Africa/Bujumbura",
				value: "Africa/Bujumbura",
				name: "Burundi",
				alpha2: "BI",
				alpha3: "BDI",
				numeric: 108,
			},
			{
				label: "Africa/Cairo",
				value: "Africa/Cairo",
				name: "Egypt",
				alpha2: "EG",
				alpha3: "EGY",
				numeric: 818,
			},
			{
				label: "Africa/Casablanca",
				value: "Africa/Casablanca",
				name: "Morocco",
				alpha2: "MA",
				alpha3: "MAR",
				numeric: 504,
			},
			{
				label: "Africa/Ceuta",
				value: "Africa/Ceuta",
				name: "Spain",
				alpha2: "ES",
				alpha3: "ESP",
				numeric: 724,
			},
			{
				label: "Africa/Conakry",
				value: "Africa/Conakry",
				name: "Guinea",
				alpha2: "GN",
				alpha3: "GIN",
				numeric: 324,
			},
			{
				label: "Africa/Dakar",
				value: "Africa/Dakar",
				name: "Senegal",
				alpha2: "SN",
				alpha3: "SEN",
				numeric: 686,
			},
			{
				label: "Africa/Dar_es_Salaam",
				value: "Africa/Dar_es_Salaam",
				name: "Tanzania, United Republic of",
				alpha2: "TZ",
				alpha3: "TZA",
				numeric: 834,
			},
			{
				label: "Africa/Djibouti",
				value: "Africa/Djibouti",
				name: "Djibouti",
				alpha2: "DJ",
				alpha3: "DJI",
				numeric: 262,
			},
			{
				label: "Africa/Douala",
				value: "Africa/Douala",
				name: "Cameroon",
				alpha2: "CM",
				alpha3: "CMR",
				numeric: 120,
			},
			{
				label: "Africa/El_Aaiun",
				value: "Africa/El_Aaiun",
				name: "Morocco",
				alpha2: "MA",
				alpha3: "MAR",
				numeric: 504,
			},
			{
				label: "Africa/Freetown",
				value: "Africa/Freetown",
				name: "Sierra Leone",
				alpha2: "SL",
				alpha3: "SLE",
				numeric: 694,
			},
			{
				label: "Africa/Gaborone",
				value: "Africa/Gaborone",
				name: "Botswana",
				alpha2: "BW",
				alpha3: "BWA",
				numeric: 72,
			},
			{
				label: "Africa/Harare",
				value: "Africa/Harare",
				name: "Zimbabwe",
				alpha2: "ZW",
				alpha3: "ZWE",
				numeric: 716,
			},
			{
				label: "Africa/Johannesburg",
				value: "Africa/Johannesburg",
				name: "South Africa",
				alpha2: "ZA",
				alpha3: "ZAF",
				numeric: 710,
			},
			{
				label: "Africa/Juba",
				value: "Africa/Juba",
				name: "South Sudan",
				alpha2: "SS",
				alpha3: "SSD",
				numeric: 728,
			},
			{
				label: "Africa/Kampala",
				value: "Africa/Kampala",
				name: "Uganda",
				alpha2: "UG",
				alpha3: "UGA",
				numeric: 800,
			},
			{
				label: "Africa/Khartoum",
				value: "Africa/Khartoum",
				name: "Sudan (the)",
				alpha2: "SD",
				alpha3: "SDN",
				numeric: 729,
			},
			{
				label: "Africa/Kigali",
				value: "Africa/Kigali",
				name: "Rwanda",
				alpha2: "RW",
				alpha3: "RWA",
				numeric: 646,
			},
			{
				label: "Africa/Kinshasa",
				value: "Africa/Kinshasa",
				name: "Congo (the Democratic Republic of the)",
				alpha2: "CD",
				alpha3: "COD",
				numeric: 180,
			},
			{
				label: "Africa/Lagos",
				value: "Africa/Lagos",
				name: "Nigeria",
				alpha2: "NG",
				alpha3: "NGA",
				numeric: 566,
			},
			{
				label: "Africa/Libreville",
				value: "Africa/Libreville",
				name: "Gabon",
				alpha2: "GA",
				alpha3: "GAB",
				numeric: 266,
			},
			{
				label: "Africa/Lome",
				value: "Africa/Lome",
				name: "Togo",
				alpha2: "TG",
				alpha3: "TGO",
				numeric: 768,
			},
			{
				label: "Africa/Luanda",
				value: "Africa/Luanda",
				name: "Angola",
				alpha2: "AO",
				alpha3: "AGO",
				numeric: 24,
			},
			{
				label: "Africa/Lubumbashi",
				value: "Africa/Lubumbashi",
				name: "Congo (the Democratic Republic of the)",
				alpha2: "CD",
				alpha3: "COD",
				numeric: 180,
			},
			{
				label: "Africa/Lusaka",
				value: "Africa/Lusaka",
				name: "Zambia",
				alpha2: "ZM",
				alpha3: "ZMB",
				numeric: 894,
			},
			{
				label: "Africa/Malabo",
				value: "Africa/Malabo",
				name: "Equatorial Guinea",
				alpha2: "GQ",
				alpha3: "GNQ",
				numeric: 226,
			},
			{
				label: "Africa/Maputo",
				value: "Africa/Maputo",
				name: "Mozambique",
				alpha2: "MZ",
				alpha3: "MOZ",
				numeric: 508,
			},
			{
				label: "Africa/Maseru",
				value: "Africa/Maseru",
				name: "Lesotho",
				alpha2: "LS",
				alpha3: "LSO",
				numeric: 426,
			},
			{
				label: "Africa/Mbabane",
				value: "Africa/Mbabane",
				name: "Eswatini",
				alpha2: "SZ",
				alpha3: "SWZ",
				numeric: 748,
			},
			{
				label: "Africa/Mogadishu",
				value: "Africa/Mogadishu",
				name: "Somalia",
				alpha2: "SO",
				alpha3: "SOM",
				numeric: 706,
			},
			{
				label: "Africa/Monrovia",
				value: "Africa/Monrovia",
				name: "Liberia",
				alpha2: "LR",
				alpha3: "LBR",
				numeric: 430,
			},
			{
				label: "Africa/Nairobi",
				value: "Africa/Nairobi",
				name: "Kenya",
				alpha2: "KE",
				alpha3: "KEN",
				numeric: 404,
			},
			{
				label: "Africa/Ndjamena",
				value: "Africa/Ndjamena",
				name: "Chad",
				alpha2: "TD",
				alpha3: "TCD",
				numeric: 148,
			},
			{
				label: "Africa/Niamey",
				value: "Africa/Niamey",
				name: "Niger (the)",
				alpha2: "NE",
				alpha3: "NER",
				numeric: 562,
			},
			{
				label: "Africa/Nouakchott",
				value: "Africa/Nouakchott",
				name: "Mauritania",
				alpha2: "MR",
				alpha3: "MRT",
				numeric: 478,
			},
			{
				label: "Africa/Ouagadougou",
				value: "Africa/Ouagadougou",
				name: "Burkina Faso",
				alpha2: "BF",
				alpha3: "BFA",
				numeric: 854,
			},
			{
				label: "Africa/Porto-Novo",
				value: "Africa/Porto-Novo",
				name: "Benin",
				alpha2: "BJ",
				alpha3: "BEN",
				numeric: 204,
			},
			{
				label: "Africa/Sao_Tome",
				value: "Africa/Sao_Tome",
				name: "Sao Tome and Principe",
				alpha2: "ST",
				alpha3: "STP",
				numeric: 678,
			},
			{
				label: "Africa/Tripoli",
				value: "Africa/Tripoli",
				name: "Libya",
				alpha2: "LY",
				alpha3: "LBY",
				numeric: 434,
			},
			{
				label: "Africa/Tunis",
				value: "Africa/Tunis",
				name: "Tunisia",
				alpha2: "TN",
				alpha3: "TUN",
				numeric: 788,
			},
			{
				label: "Africa/Windhoek",
				value: "Africa/Windhoek",
				name: "Namibia",
				alpha2: "NA",
				alpha3: "NAM",
				numeric: 516,
			},
		],
	},
	{
		label: "America",
		options: [
			{
				label: "America/Adak",
				value: "America/Adak",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Anchorage",
				value: "America/Anchorage",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Anguilla",
				value: "America/Anguilla",
				name: "Anguilla",
				alpha2: "AI",
				alpha3: "AIA",
				numeric: 660,
			},
			{
				label: "America/Antigua",
				value: "America/Antigua",
				name: "Antigua and Barbuda",
				alpha2: "AG",
				alpha3: "ATG",
				numeric: 28,
			},
			{
				label: "America/Araguaina",
				value: "America/Araguaina",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Argentina/Buenos_Aires",
				value: "America/Argentina/Buenos_Aires",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Catamarca",
				value: "America/Argentina/Catamarca",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Cordoba",
				value: "America/Argentina/Cordoba",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Jujuy",
				value: "America/Argentina/Jujuy",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/La_Rioja",
				value: "America/Argentina/La_Rioja",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Mendoza",
				value: "America/Argentina/Mendoza",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Rio_Gallegos",
				value: "America/Argentina/Rio_Gallegos",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Salta",
				value: "America/Argentina/Salta",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/San_Juan",
				value: "America/Argentina/San_Juan",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/San_Luis",
				value: "America/Argentina/San_Luis",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Tucuman",
				value: "America/Argentina/Tucuman",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Argentina/Ushuaia",
				value: "America/Argentina/Ushuaia",
				name: "Argentina",
				alpha2: "AR",
				alpha3: "ARG",
				numeric: 32,
			},
			{
				label: "America/Aruba",
				value: "America/Aruba",
				name: "Aruba",
				alpha2: "AW",
				alpha3: "ABW",
				numeric: 533,
			},
			{
				label: "America/Asuncion",
				value: "America/Asuncion",
				name: "Paraguay",
				alpha2: "PY",
				alpha3: "PRY",
				numeric: 600,
			},
			{
				label: "America/Atikokan",
				value: "America/Atikokan",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Bahia_Banderas",
				value: "America/Bahia_Banderas",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Bahia",
				value: "America/Bahia",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Barbados",
				value: "America/Barbados",
				name: "Barbados",
				alpha2: "BB",
				alpha3: "BRB",
				numeric: 52,
			},
			{
				label: "America/Belem",
				value: "America/Belem",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Belize",
				value: "America/Belize",
				name: "Belize",
				alpha2: "BZ",
				alpha3: "BLZ",
				numeric: 84,
			},
			{
				label: "America/Blanc-Sablon",
				value: "America/Blanc-Sablon",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Boa_Vista",
				value: "America/Boa_Vista",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Bogota",
				value: "America/Bogota",
				name: "Colombia",
				alpha2: "CO",
				alpha3: "COL",
				numeric: 170,
			},
			{
				label: "America/Boise",
				value: "America/Boise",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Cambridge_Bay",
				value: "America/Cambridge_Bay",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Campo_Grande",
				value: "America/Campo_Grande",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Cancun",
				value: "America/Cancun",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Caracas",
				value: "America/Caracas",
				name: "Venezuela (Bolivarian Republic of)",
				alpha2: "VE",
				alpha3: "VEN",
				numeric: 862,
			},
			{
				label: "America/Cayenne",
				value: "America/Cayenne",
				name: "French Guiana",
				alpha2: "GF",
				alpha3: "GUF",
				numeric: 254,
			},
			{
				label: "America/Cayman",
				value: "America/Cayman",
				name: "Cayman Islands (the)",
				alpha2: "KY",
				alpha3: "CYM",
				numeric: 136,
			},
			{
				label: "America/Chicago",
				value: "America/Chicago",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Chihuahua",
				value: "America/Chihuahua",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Ciudad_Juarez",
				value: "America/Ciudad_Juarez",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Costa_Rica",
				value: "America/Costa_Rica",
				name: "Costa Rica",
				alpha2: "CR",
				alpha3: "CRI",
				numeric: 188,
			},
			{
				label: "America/Creston",
				value: "America/Creston",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Cuiaba",
				value: "America/Cuiaba",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Curacao",
				value: "America/Curacao",
				name: "Curaçao",
				alpha2: "CW",
				alpha3: "CUW",
				numeric: 531,
			},
			{
				label: "America/Danmarkshavn",
				value: "America/Danmarkshavn",
				name: "Greenland",
				alpha2: "GL",
				alpha3: "GRL",
				numeric: 304,
			},
			{
				label: "America/Dawson",
				value: "America/Dawson",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Dawson_Creek",
				value: "America/Dawson_Creek",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Denver",
				value: "America/Denver",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Detroit",
				value: "America/Detroit",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Dominica",
				value: "America/Dominica",
				name: "Dominica",
				alpha2: "DM",
				alpha3: "DMA",
				numeric: 212,
			},
			{
				label: "America/Edmonton",
				value: "America/Edmonton",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Eirunepe",
				value: "America/Eirunepe",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/El_Salvador",
				value: "America/El_Salvador",
				name: "El Salvador",
				alpha2: "SV",
				alpha3: "SLV",
				numeric: 222,
			},
			{
				label: "America/Fortaleza",
				value: "America/Fortaleza",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Fort_Nelson",
				value: "America/Fort_Nelson",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Glace_Bay",
				value: "America/Glace_Bay",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Goose_Bay",
				value: "America/Goose_Bay",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Grand_Turk",
				value: "America/Grand_Turk",
				name: "Turks and Caicos Islands (the)",
				alpha2: "TC",
				alpha3: "TCA",
				numeric: 796,
			},
			{
				label: "America/Grenada",
				value: "America/Grenada",
				name: "Grenada",
				alpha2: "GD",
				alpha3: "GRD",
				numeric: 308,
			},
			{
				label: "America/Guadeloupe",
				value: "America/Guadeloupe",
				name: "Guadeloupe",
				alpha2: "GP",
				alpha3: "GLP",
				numeric: 312,
			},
			{
				label: "America/Guatemala",
				value: "America/Guatemala",
				name: "Guatemala",
				alpha2: "GT",
				alpha3: "GTM",
				numeric: 320,
			},
			{
				label: "America/Guayaquil",
				value: "America/Guayaquil",
				name: "Ecuador",
				alpha2: "EC",
				alpha3: "ECU",
				numeric: 218,
			},
			{
				label: "America/Guyana",
				value: "America/Guyana",
				name: "Guyana",
				alpha2: "GY",
				alpha3: "GUY",
				numeric: 328,
			},
			{
				label: "America/Halifax",
				value: "America/Halifax",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Havana",
				value: "America/Havana",
				name: "Cuba",
				alpha2: "CU",
				alpha3: "CUB",
				numeric: 192,
			},
			{
				label: "America/Hermosillo",
				value: "America/Hermosillo",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Indiana/Indianapolis",
				value: "America/Indiana/Indianapolis",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Knox",
				value: "America/Indiana/Knox",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Marengo",
				value: "America/Indiana/Marengo",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Petersburg",
				value: "America/Indiana/Petersburg",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Tell_City",
				value: "America/Indiana/Tell_City",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Vevay",
				value: "America/Indiana/Vevay",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Vincennes",
				value: "America/Indiana/Vincennes",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Indiana/Winamac",
				value: "America/Indiana/Winamac",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Inuvik",
				value: "America/Inuvik",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Iqaluit",
				value: "America/Iqaluit",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Jamaica",
				value: "America/Jamaica",
				name: "Jamaica",
				alpha2: "JM",
				alpha3: "JAM",
				numeric: 388,
			},
			{
				label: "America/Juneau",
				value: "America/Juneau",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Kentucky/Louisville",
				value: "America/Kentucky/Louisville",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Kentucky/Monticello",
				value: "America/Kentucky/Monticello",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Kralendijk",
				value: "America/Kralendijk",
				name: "Bonaire, Sint Eustatius and Saba",
				alpha2: "BQ",
				alpha3: "BES",
				numeric: 535,
			},
			{
				label: "America/La_Paz",
				value: "America/La_Paz",
				name: "Bolivia (Plurinational State of)",
				alpha2: "BO",
				alpha3: "BOL",
				numeric: 68,
			},
			{
				label: "America/Lima",
				value: "America/Lima",
				name: "Peru",
				alpha2: "PE",
				alpha3: "PER",
				numeric: 604,
			},
			{
				label: "America/Los_Angeles",
				value: "America/Los_Angeles",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Lower_Princes",
				value: "America/Lower_Princes",
				name: "Sint Maarten (Dutch part)",
				alpha2: "SX",
				alpha3: "SXM",
				numeric: 534,
			},
			{
				label: "America/Maceio",
				value: "America/Maceio",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Managua",
				value: "America/Managua",
				name: "Nicaragua",
				alpha2: "NI",
				alpha3: "NIC",
				numeric: 558,
			},
			{
				label: "America/Manaus",
				value: "America/Manaus",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Marigot",
				value: "America/Marigot",
				name: "Saint Martin (French part)",
				alpha2: "MF",
				alpha3: "MAF",
				numeric: 663,
			},
			{
				label: "America/Martinique",
				value: "America/Martinique",
				name: "Martinique",
				alpha2: "MQ",
				alpha3: "MTQ",
				numeric: 474,
			},
			{
				label: "America/Matamoros",
				value: "America/Matamoros",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Mazatlan",
				value: "America/Mazatlan",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Menominee",
				value: "America/Menominee",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Merida",
				value: "America/Merida",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Metlakatla",
				value: "America/Metlakatla",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Mexico_City",
				value: "America/Mexico_City",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Miquelon",
				value: "America/Miquelon",
				name: "Saint Pierre and Miquelon",
				alpha2: "PM",
				alpha3: "SPM",
				numeric: 666,
			},
			{
				label: "America/Moncton",
				value: "America/Moncton",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Monterrey",
				value: "America/Monterrey",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Montevideo",
				value: "America/Montevideo",
				name: "Uruguay",
				alpha2: "UY",
				alpha3: "URY",
				numeric: 858,
			},
			{
				label: "America/Montserrat",
				value: "America/Montserrat",
				name: "Montserrat",
				alpha2: "MS",
				alpha3: "MSR",
				numeric: 500,
			},
			{
				label: "America/Nassau",
				value: "America/Nassau",
				name: "Bahamas (the)",
				alpha2: "BS",
				alpha3: "BHS",
				numeric: 44,
			},
			{
				label: "America/New_York",
				value: "America/New_York",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Nome",
				value: "America/Nome",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Noronha",
				value: "America/Noronha",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/North_Dakota/Beulah",
				value: "America/North_Dakota/Beulah",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/North_Dakota/Center",
				value: "America/North_Dakota/Center",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/North_Dakota/New_Salem",
				value: "America/North_Dakota/New_Salem",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Nuuk",
				value: "America/Nuuk",
				name: "Greenland",
				alpha2: "GL",
				alpha3: "GRL",
				numeric: 304,
			},
			{
				label: "America/Ojinaga",
				value: "America/Ojinaga",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Panama",
				value: "America/Panama",
				name: "Panama",
				alpha2: "PA",
				alpha3: "PAN",
				numeric: 591,
			},
			{
				label: "America/Paramaribo",
				value: "America/Paramaribo",
				name: "Suriname",
				alpha2: "SR",
				alpha3: "SUR",
				numeric: 740,
			},
			{
				label: "America/Phoenix",
				value: "America/Phoenix",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/Port-au-Prince",
				value: "America/Port-au-Prince",
				name: "Haiti",
				alpha2: "HT",
				alpha3: "HTI",
				numeric: 332,
			},
			{
				label: "America/Port_of_Spain",
				value: "America/Port_of_Spain",
				name: "Trinidad and Tobago",
				alpha2: "TT",
				alpha3: "TTO",
				numeric: 780,
			},
			{
				label: "America/Porto_Velho",
				value: "America/Porto_Velho",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Puerto_Rico",
				value: "America/Puerto_Rico",
				name: "Puerto Rico",
				alpha2: "PR",
				alpha3: "PRI",
				numeric: 630,
			},
			{
				label: "America/Punta_Arenas",
				value: "America/Punta_Arenas",
				name: "Chile",
				alpha2: "CL",
				alpha3: "CHL",
				numeric: 152,
			},
			{
				label: "America/Rankin_Inlet",
				value: "America/Rankin_Inlet",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Recife",
				value: "America/Recife",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Regina",
				value: "America/Regina",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Resolute",
				value: "America/Resolute",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Rio_Branco",
				value: "America/Rio_Branco",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Santarem",
				value: "America/Santarem",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Santiago",
				value: "America/Santiago",
				name: "Chile",
				alpha2: "CL",
				alpha3: "CHL",
				numeric: 152,
			},
			{
				label: "America/Santo_Domingo",
				value: "America/Santo_Domingo",
				name: "Dominican Republic (the)",
				alpha2: "DO",
				alpha3: "DOM",
				numeric: 214,
			},
			{
				label: "America/Sao_Paulo",
				value: "America/Sao_Paulo",
				name: "Brazil",
				alpha2: "BR",
				alpha3: "BRA",
				numeric: 76,
			},
			{
				label: "America/Scoresbysund",
				value: "America/Scoresbysund",
				name: "Greenland",
				alpha2: "GL",
				alpha3: "GRL",
				numeric: 304,
			},
			{
				label: "America/Sitka",
				value: "America/Sitka",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "America/St_Barthelemy",
				value: "America/St_Barthelemy",
				name: "Saint Barthélemy",
				alpha2: "BL",
				alpha3: "BLM",
				numeric: 652,
			},
			{
				label: "America/St_Johns",
				value: "America/St_Johns",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/St_Kitts",
				value: "America/St_Kitts",
				name: "Saint Kitts and Nevis",
				alpha2: "KN",
				alpha3: "KNA",
				numeric: 659,
			},
			{
				label: "America/St_Lucia",
				value: "America/St_Lucia",
				name: "Saint Lucia",
				alpha2: "LC",
				alpha3: "LCA",
				numeric: 662,
			},
			{
				label: "America/St_Thomas",
				value: "America/St_Thomas",
				name: "Virgin Islands (U.S.)",
				alpha2: "VI",
				alpha3: "VIR",
				numeric: 850,
			},
			{
				label: "America/St_Vincent",
				value: "America/St_Vincent",
				name: "Saint Vincent and the Grenadines",
				alpha2: "VC",
				alpha3: "VCT",
				numeric: 670,
			},
			{
				label: "America/Swift_Current",
				value: "America/Swift_Current",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Tegucigalpa",
				value: "America/Tegucigalpa",
				name: "Honduras",
				alpha2: "HN",
				alpha3: "HND",
				numeric: 340,
			},
			{
				label: "America/Thule",
				value: "America/Thule",
				name: "Greenland",
				alpha2: "GL",
				alpha3: "GRL",
				numeric: 304,
			},
			{
				label: "America/Tijuana",
				value: "America/Tijuana",
				name: "Mexico",
				alpha2: "MX",
				alpha3: "MEX",
				numeric: 484,
			},
			{
				label: "America/Toronto",
				value: "America/Toronto",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Tortola",
				value: "America/Tortola",
				name: "Virgin Islands (British)",
				alpha2: "VG",
				alpha3: "VGB",
				numeric: 92,
			},
			{
				label: "America/Vancouver",
				value: "America/Vancouver",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Whitehorse",
				value: "America/Whitehorse",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Winnipeg",
				value: "America/Winnipeg",
				name: "Canada",
				alpha2: "CA",
				alpha3: "CAN",
				numeric: 124,
			},
			{
				label: "America/Yakutat",
				value: "America/Yakutat",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
		],
	},
	{
		label: "Antarctica",
		options: [
			{
				label: "Antarctica/Casey",
				value: "Antarctica/Casey",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Davis",
				value: "Antarctica/Davis",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/DumontDUrville",
				value: "Antarctica/DumontDUrville",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Macquarie",
				value: "Antarctica/Macquarie",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Antarctica/Mawson",
				value: "Antarctica/Mawson",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/McMurdo",
				value: "Antarctica/McMurdo",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Palmer",
				value: "Antarctica/Palmer",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Rothera",
				value: "Antarctica/Rothera",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Syowa",
				value: "Antarctica/Syowa",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Troll",
				value: "Antarctica/Troll",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
			{
				label: "Antarctica/Vostok",
				value: "Antarctica/Vostok",
				name: "Antarctica",
				alpha2: "AQ",
				alpha3: "ATA",
				numeric: 10,
			},
		],
	},
	{
		label: "Arctic",
		options: [
			{
				label: "Arctic/Longyearbyen",
				value: "Arctic/Longyearbyen",
				name: "Svalbard and Jan Mayen",
				alpha2: "SJ",
				alpha3: "SJM",
				numeric: 744,
			},
		],
	},
	{
		label: "Asia",
		options: [
			{
				label: "Asia/Aden",
				value: "Asia/Aden",
				name: "Yemen",
				alpha2: "YE",
				alpha3: "YEM",
				numeric: 887,
			},
			{
				label: "Asia/Almaty",
				value: "Asia/Almaty",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Amman",
				value: "Asia/Amman",
				name: "Jordan",
				alpha2: "JO",
				alpha3: "JOR",
				numeric: 400,
			},
			{
				label: "Asia/Anadyr",
				value: "Asia/Anadyr",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Aqtau",
				value: "Asia/Aqtau",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Aqtobe",
				value: "Asia/Aqtobe",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Ashgabat",
				value: "Asia/Ashgabat",
				name: "Turkmenistan",
				alpha2: "TM",
				alpha3: "TKM",
				numeric: 795,
			},
			{
				label: "Asia/Atyrau",
				value: "Asia/Atyrau",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Baghdad",
				value: "Asia/Baghdad",
				name: "Iraq",
				alpha2: "IQ",
				alpha3: "IRQ",
				numeric: 368,
			},
			{
				label: "Asia/Bahrain",
				value: "Asia/Bahrain",
				name: "Bahrain",
				alpha2: "BH",
				alpha3: "BHR",
				numeric: 48,
			},
			{
				label: "Asia/Baku",
				value: "Asia/Baku",
				name: "Azerbaijan",
				alpha2: "AZ",
				alpha3: "AZE",
				numeric: 31,
			},
			{
				label: "Asia/Bangkok",
				value: "Asia/Bangkok",
				name: "Thailand",
				alpha2: "TH",
				alpha3: "THA",
				numeric: 764,
			},
			{
				label: "Asia/Barnaul",
				value: "Asia/Barnaul",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Beirut",
				value: "Asia/Beirut",
				name: "Lebanon",
				alpha2: "LB",
				alpha3: "LBN",
				numeric: 422,
			},
			{
				label: "Asia/Bishkek",
				value: "Asia/Bishkek",
				name: "Kyrgyzstan",
				alpha2: "KG",
				alpha3: "KGZ",
				numeric: 417,
			},
			{
				label: "Asia/Brunei",
				value: "Asia/Brunei",
				name: "Brunei Darussalam",
				alpha2: "BN",
				alpha3: "BRN",
				numeric: 96,
			},
			{
				label: "Asia/Chita",
				value: "Asia/Chita",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Choibalsan",
				value: "Asia/Choibalsan",
				name: "Mongolia",
				alpha2: "MN",
				alpha3: "MNG",
				numeric: 496,
			},
			{
				label: "Asia/Colombo",
				value: "Asia/Colombo",
				name: "Sri Lanka",
				alpha2: "LK",
				alpha3: "LKA",
				numeric: 144,
			},
			{
				label: "Asia/Damascus",
				value: "Asia/Damascus",
				name: "Syrian Arab Republic",
				alpha2: "SY",
				alpha3: "SYR",
				numeric: 760,
			},
			{
				label: "Asia/Dhaka",
				value: "Asia/Dhaka",
				name: "Bangladesh",
				alpha2: "BD",
				alpha3: "BGD",
				numeric: 50,
			},
			{
				label: "Asia/Dili",
				value: "Asia/Dili",
				name: "Timor-Leste",
				alpha2: "TL",
				alpha3: "TLS",
				numeric: 626,
			},
			{
				label: "Asia/Dubai",
				value: "Asia/Dubai",
				name: "United Arab Emirates (the)",
				alpha2: "AE",
				alpha3: "ARE",
				numeric: 784,
			},
			{
				label: "Asia/Dushanbe",
				value: "Asia/Dushanbe",
				name: "Tajikistan",
				alpha2: "TJ",
				alpha3: "TJK",
				numeric: 762,
			},
			{
				label: "Asia/Famagusta",
				value: "Asia/Famagusta",
				name: "Cyprus",
				alpha2: "CY",
				alpha3: "CYP",
				numeric: 196,
			},
			{
				label: "Asia/Gaza",
				value: "Asia/Gaza",
				name: "Palestine, State of",
				alpha2: "PS",
				alpha3: "PSE",
				numeric: 275,
			},
			{
				label: "Asia/Hebron",
				value: "Asia/Hebron",
				name: "Palestine, State of",
				alpha2: "PS",
				alpha3: "PSE",
				numeric: 275,
			},
			{
				label: "Asia/Ho_Chi_Minh",
				value: "Asia/Ho_Chi_Minh",
				name: "Viet Nam",
				alpha2: "VN",
				alpha3: "VNM",
				numeric: 704,
			},
			{
				label: "Asia/Hong_Kong",
				value: "Asia/Hong_Kong",
				name: "Hong Kong",
				alpha2: "HK",
				alpha3: "HKG",
				numeric: 344,
			},
			{
				label: "Asia/Hovd",
				value: "Asia/Hovd",
				name: "Mongolia",
				alpha2: "MN",
				alpha3: "MNG",
				numeric: 496,
			},
			{
				label: "Asia/Irkutsk",
				value: "Asia/Irkutsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Jakarta",
				value: "Asia/Jakarta",
				name: "Indonesia",
				alpha2: "ID",
				alpha3: "IDN",
				numeric: 360,
			},
			{
				label: "Asia/Jayapura",
				value: "Asia/Jayapura",
				name: "Indonesia",
				alpha2: "ID",
				alpha3: "IDN",
				numeric: 360,
			},
			{
				label: "Asia/Jerusalem",
				value: "Asia/Jerusalem",
				name: "Israel",
				alpha2: "IL",
				alpha3: "ISR",
				numeric: 376,
			},
			{
				label: "Asia/Kabul",
				value: "Asia/Kabul",
				name: "Afghanistan",
				alpha2: "AF",
				alpha3: "AFG",
				numeric: 4,
			},
			{
				label: "Asia/Kamchatka",
				value: "Asia/Kamchatka",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Karachi",
				value: "Asia/Karachi",
				name: "Pakistan",
				alpha2: "PK",
				alpha3: "PAK",
				numeric: 586,
			},
			{
				label: "Asia/Kathmandu",
				value: "Asia/Kathmandu",
				name: "Nepal",
				alpha2: "NP",
				alpha3: "NPL",
				numeric: 524,
			},
			{
				label: "Asia/Khandyga",
				value: "Asia/Khandyga",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Kolkata",
				value: "Asia/Kolkata",
				name: "India",
				alpha2: "IN",
				alpha3: "IND",
				numeric: 356,
			},
			{
				label: "Asia/Krasnoyarsk",
				value: "Asia/Krasnoyarsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Kuala_Lumpur",
				value: "Asia/Kuala_Lumpur",
				name: "Malaysia",
				alpha2: "MY",
				alpha3: "MYS",
				numeric: 458,
			},
			{
				label: "Asia/Kuching",
				value: "Asia/Kuching",
				name: "Malaysia",
				alpha2: "MY",
				alpha3: "MYS",
				numeric: 458,
			},
			{
				label: "Asia/Kuwait",
				value: "Asia/Kuwait",
				name: "Kuwait",
				alpha2: "KW",
				alpha3: "KWT",
				numeric: 414,
			},
			{
				label: "Asia/Macau",
				value: "Asia/Macau",
				name: "Macao",
				alpha2: "MO",
				alpha3: "MAC",
				numeric: 446,
			},
			{
				label: "Asia/Magadan",
				value: "Asia/Magadan",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Makassar",
				value: "Asia/Makassar",
				name: "Indonesia",
				alpha2: "ID",
				alpha3: "IDN",
				numeric: 360,
			},
			{
				label: "Asia/Manila",
				value: "Asia/Manila",
				name: "Philippines (the)",
				alpha2: "PH",
				alpha3: "PHL",
				numeric: 608,
			},
			{
				label: "Asia/Muscat",
				value: "Asia/Muscat",
				name: "Oman",
				alpha2: "OM",
				alpha3: "OMN",
				numeric: 512,
			},
			{
				label: "Asia/Nicosia",
				value: "Asia/Nicosia",
				name: "Cyprus",
				alpha2: "CY",
				alpha3: "CYP",
				numeric: 196,
			},
			{
				label: "Asia/Novokuznetsk",
				value: "Asia/Novokuznetsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Novosibirsk",
				value: "Asia/Novosibirsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Omsk",
				value: "Asia/Omsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Oral",
				value: "Asia/Oral",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Phnom_Penh",
				value: "Asia/Phnom_Penh",
				name: "Cambodia",
				alpha2: "KH",
				alpha3: "KHM",
				numeric: 116,
			},
			{
				label: "Asia/Pontianak",
				value: "Asia/Pontianak",
				name: "Indonesia",
				alpha2: "ID",
				alpha3: "IDN",
				numeric: 360,
			},
			{
				label: "Asia/Pyongyang",
				value: "Asia/Pyongyang",
				name: "Korea (the Democratic People's Republic of)",
				alpha2: "KP",
				alpha3: "PRK",
				numeric: 408,
			},
			{
				label: "Asia/Qatar",
				value: "Asia/Qatar",
				name: "Qatar",
				alpha2: "QA",
				alpha3: "QAT",
				numeric: 634,
			},
			{
				label: "Asia/Qostanay",
				value: "Asia/Qostanay",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Qyzylorda",
				value: "Asia/Qyzylorda",
				name: "Kazakhstan",
				alpha2: "KZ",
				alpha3: "KAZ",
				numeric: 398,
			},
			{
				label: "Asia/Riyadh",
				value: "Asia/Riyadh",
				name: "Saudi Arabia",
				alpha2: "SA",
				alpha3: "SAU",
				numeric: 682,
			},
			{
				label: "Asia/Sakhalin",
				value: "Asia/Sakhalin",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Samarkand",
				value: "Asia/Samarkand",
				name: "Uzbekistan",
				alpha2: "UZ",
				alpha3: "UZB",
				numeric: 860,
			},
			{
				label: "Asia/Seoul",
				value: "Asia/Seoul",
				name: "Korea (the Republic of)",
				alpha2: "KR",
				alpha3: "KOR",
				numeric: 410,
			},
			{
				label: "Asia/Shanghai",
				value: "Asia/Shanghai",
				name: "China",
				alpha2: "CN",
				alpha3: "CHN",
				numeric: 156,
			},
			{
				label: "Asia/Singapore",
				value: "Asia/Singapore",
				name: "Singapore",
				alpha2: "SG",
				alpha3: "SGP",
				numeric: 702,
			},
			{
				label: "Asia/Srednekolymsk",
				value: "Asia/Srednekolymsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Taipei",
				value: "Asia/Taipei",
				name: "Taiwan (Province of China)",
				alpha2: "TW",
				alpha3: "TWN",
				numeric: 158,
			},
			{
				label: "Asia/Tashkent",
				value: "Asia/Tashkent",
				name: "Uzbekistan",
				alpha2: "UZ",
				alpha3: "UZB",
				numeric: 860,
			},
			{
				label: "Asia/Tbilisi",
				value: "Asia/Tbilisi",
				name: "Georgia",
				alpha2: "GE",
				alpha3: "GEO",
				numeric: 268,
			},
			{
				label: "Asia/Tehran",
				value: "Asia/Tehran",
				name: "Iran (Islamic Republic of)",
				alpha2: "IR",
				alpha3: "IRN",
				numeric: 364,
			},
			{
				label: "Asia/Thimphu",
				value: "Asia/Thimphu",
				name: "Bhutan",
				alpha2: "BT",
				alpha3: "BTN",
				numeric: 64,
			},
			{
				label: "Asia/Tokyo",
				value: "Asia/Tokyo",
				name: "Japan",
				alpha2: "JP",
				alpha3: "JPN",
				numeric: 392,
			},
			{
				label: "Asia/Tomsk",
				value: "Asia/Tomsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Ulaanbaatar",
				value: "Asia/Ulaanbaatar",
				name: "Mongolia",
				alpha2: "MN",
				alpha3: "MNG",
				numeric: 496,
			},
			{
				label: "Asia/Urumqi",
				value: "Asia/Urumqi",
				name: "China",
				alpha2: "CN",
				alpha3: "CHN",
				numeric: 156,
			},
			{
				label: "Asia/Ust-Nera",
				value: "Asia/Ust-Nera",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Vientiane",
				value: "Asia/Vientiane",
				name: "Lao People's Democratic Republic (the)",
				alpha2: "LA",
				alpha3: "LAO",
				numeric: 418,
			},
			{
				label: "Asia/Vladivostok",
				value: "Asia/Vladivostok",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Yakutsk",
				value: "Asia/Yakutsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Yangon",
				value: "Asia/Yangon",
				name: "Myanmar",
				alpha2: "MM",
				alpha3: "MMR",
				numeric: 104,
			},
			{
				label: "Asia/Yekaterinburg",
				value: "Asia/Yekaterinburg",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Asia/Yerevan",
				value: "Asia/Yerevan",
				name: "Armenia",
				alpha2: "AM",
				alpha3: "ARM",
				numeric: 51,
			},
		],
	},
	{
		label: "Atlantic",
		options: [
			{
				label: "Atlantic/Azores",
				value: "Atlantic/Azores",
				name: "Portugal",
				alpha2: "PT",
				alpha3: "PRT",
				numeric: 620,
			},
			{
				label: "Atlantic/Bermuda",
				value: "Atlantic/Bermuda",
				name: "Bermuda",
				alpha2: "BM",
				alpha3: "BMU",
				numeric: 60,
			},
			{
				label: "Atlantic/Canary",
				value: "Atlantic/Canary",
				name: "Spain",
				alpha2: "ES",
				alpha3: "ESP",
				numeric: 724,
			},
			{
				label: "Atlantic/Cape_Verde",
				value: "Atlantic/Cape_Verde",
				name: "Cabo Verde",
				alpha2: "CV",
				alpha3: "CPV",
				numeric: 132,
			},
			{
				label: "Atlantic/Faroe",
				value: "Atlantic/Faroe",
				name: "Faroe Islands (the)",
				alpha2: "FO",
				alpha3: "FRO",
				numeric: 234,
			},
			{
				label: "Atlantic/Madeira",
				value: "Atlantic/Madeira",
				name: "Portugal",
				alpha2: "PT",
				alpha3: "PRT",
				numeric: 620,
			},
			{
				label: "Atlantic/Reykjavik",
				value: "Atlantic/Reykjavik",
				name: "Iceland",
				alpha2: "IS",
				alpha3: "ISL",
				numeric: 352,
			},
			{
				label: "Atlantic/South_Georgia",
				value: "Atlantic/South_Georgia",
				name: "South Georgia and the South Sandwich Islands",
				alpha2: "GS",
				alpha3: "SGS",
				numeric: 239,
			},
			{
				label: "Atlantic/Stanley",
				value: "Atlantic/Stanley",
				name: "Falkland Islands (the) [Malvinas]",
				alpha2: "FK",
				alpha3: "FLK",
				numeric: 238,
			},
			{
				label: "Atlantic/St_Helena",
				value: "Atlantic/St_Helena",
				name: "Saint Helena, Ascension and Tristan da Cunha",
				alpha2: "SH",
				alpha3: "SHN",
				numeric: 654,
			},
		],
	},
	{
		label: "Australia",
		options: [
			{
				label: "Australia/Adelaide",
				value: "Australia/Adelaide",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Brisbane",
				value: "Australia/Brisbane",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Broken_Hill",
				value: "Australia/Broken_Hill",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Darwin",
				value: "Australia/Darwin",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Eucla",
				value: "Australia/Eucla",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Hobart",
				value: "Australia/Hobart",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Lindeman",
				value: "Australia/Lindeman",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Lord_Howe",
				value: "Australia/Lord_Howe",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Melbourne",
				value: "Australia/Melbourne",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Perth",
				value: "Australia/Perth",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
			{
				label: "Australia/Sydney",
				value: "Australia/Sydney",
				name: "Australia",
				alpha2: "AU",
				alpha3: "AUS",
				numeric: 36,
			},
		],
	},
	{
		label: "Europe",
		options: [
			{
				label: "Europe/Amsterdam",
				value: "Europe/Amsterdam",
				name: "Netherlands (the)",
				alpha2: "NL",
				alpha3: "NLD",
				numeric: 528,
			},
			{
				label: "Europe/Andorra",
				value: "Europe/Andorra",
				name: "Andorra",
				alpha2: "AD",
				alpha3: "AND",
				numeric: 20,
			},
			{
				label: "Europe/Astrakhan",
				value: "Europe/Astrakhan",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Athens",
				value: "Europe/Athens",
				name: "Greece",
				alpha2: "GR",
				alpha3: "GRC",
				numeric: 300,
			},
			{
				label: "Europe/Belgrade",
				value: "Europe/Belgrade",
				name: "Serbia",
				alpha2: "RS",
				alpha3: "SRB",
				numeric: 688,
			},
			{
				label: "Europe/Berlin",
				value: "Europe/Berlin",
				name: "Germany",
				alpha2: "DE",
				alpha3: "DEU",
				numeric: 276,
			},
			{
				label: "Europe/Bratislava",
				value: "Europe/Bratislava",
				name: "Slovakia",
				alpha2: "SK",
				alpha3: "SVK",
				numeric: 703,
			},
			{
				label: "Europe/Brussels",
				value: "Europe/Brussels",
				name: "Belgium",
				alpha2: "BE",
				alpha3: "BEL",
				numeric: 56,
			},
			{
				label: "Europe/Bucharest",
				value: "Europe/Bucharest",
				name: "Romania",
				alpha2: "RO",
				alpha3: "ROU",
				numeric: 642,
			},
			{
				label: "Europe/Budapest",
				value: "Europe/Budapest",
				name: "Hungary",
				alpha2: "HU",
				alpha3: "HUN",
				numeric: 348,
			},
			{
				label: "Europe/Busingen",
				value: "Europe/Busingen",
				name: "Germany",
				alpha2: "DE",
				alpha3: "DEU",
				numeric: 276,
			},
			{
				label: "Europe/Chisinau",
				value: "Europe/Chisinau",
				name: "Moldova (the Republic of)",
				alpha2: "MD",
				alpha3: "MDA",
				numeric: 498,
			},
			{
				label: "Europe/Copenhagen",
				value: "Europe/Copenhagen",
				name: "Denmark",
				alpha2: "DK",
				alpha3: "DNK",
				numeric: 208,
			},
			{
				label: "Europe/Dublin",
				value: "Europe/Dublin",
				name: "Ireland",
				alpha2: "IE",
				alpha3: "IRL",
				numeric: 372,
			},
			{
				label: "Europe/Gibraltar",
				value: "Europe/Gibraltar",
				name: "Gibraltar",
				alpha2: "GI",
				alpha3: "GIB",
				numeric: 292,
			},
			{
				label: "Europe/Guernsey",
				value: "Europe/Guernsey",
				name: "Guernsey",
				alpha2: "GG",
				alpha3: "GGY",
				numeric: 831,
			},
			{
				label: "Europe/Helsinki",
				value: "Europe/Helsinki",
				name: "Finland",
				alpha2: "FI",
				alpha3: "FIN",
				numeric: 246,
			},
			{
				label: "Europe/Isle_of_Man",
				value: "Europe/Isle_of_Man",
				name: "Isle of Man",
				alpha2: "IM",
				alpha3: "IMN",
				numeric: 833,
			},
			{
				label: "Europe/Istanbul",
				value: "Europe/Istanbul",
				name: "Turkey",
				alpha2: "TR",
				alpha3: "TUR",
				numeric: 792,
			},
			{
				label: "Europe/Jersey",
				value: "Europe/Jersey",
				name: "Jersey",
				alpha2: "JE",
				alpha3: "JEY",
				numeric: 832,
			},
			{
				label: "Europe/Kaliningrad",
				value: "Europe/Kaliningrad",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Kirov",
				value: "Europe/Kirov",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Kyiv",
				value: "Europe/Kyiv",
				name: "Ukraine",
				alpha2: "UA",
				alpha3: "UKR",
				numeric: 804,
			},
			{
				label: "Europe/Lisbon",
				value: "Europe/Lisbon",
				name: "Portugal",
				alpha2: "PT",
				alpha3: "PRT",
				numeric: 620,
			},
			{
				label: "Europe/Ljubljana",
				value: "Europe/Ljubljana",
				name: "Slovenia",
				alpha2: "SI",
				alpha3: "SVN",
				numeric: 705,
			},
			{
				label: "Europe/London",
				value: "Europe/London",
				name: "United Kingdom of Great Britain and Northern Ireland (the)",
				alpha2: "GB",
				alpha3: "GBR",
				numeric: 826,
			},
			{
				label: "Europe/Luxembourg",
				value: "Europe/Luxembourg",
				name: "Luxembourg",
				alpha2: "LU",
				alpha3: "LUX",
				numeric: 442,
			},
			{
				label: "Europe/Madrid",
				value: "Europe/Madrid",
				name: "Spain",
				alpha2: "ES",
				alpha3: "ESP",
				numeric: 724,
			},
			{
				label: "Europe/Malta",
				value: "Europe/Malta",
				name: "Malta",
				alpha2: "MT",
				alpha3: "MLT",
				numeric: 470,
			},
			{
				label: "Europe/Mariehamn",
				value: "Europe/Mariehamn",
				name: "Åland Islands",
				alpha2: "AX",
				alpha3: "ALA",
				numeric: 248,
			},
			{
				label: "Europe/Minsk",
				value: "Europe/Minsk",
				name: "Belarus",
				alpha2: "BY",
				alpha3: "BLR",
				numeric: 112,
			},
			{
				label: "Europe/Monaco",
				value: "Europe/Monaco",
				name: "Monaco",
				alpha2: "MC",
				alpha3: "MCO",
				numeric: 492,
			},
			{
				label: "Europe/Moscow",
				value: "Europe/Moscow",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Oslo",
				value: "Europe/Oslo",
				name: "Norway",
				alpha2: "NO",
				alpha3: "NOR",
				numeric: 578,
			},
			{
				label: "Europe/Paris",
				value: "Europe/Paris",
				name: "France",
				alpha2: "FR",
				alpha3: "FRA",
				numeric: 250,
			},
			{
				label: "Europe/Podgorica",
				value: "Europe/Podgorica",
				name: "Montenegro",
				alpha2: "ME",
				alpha3: "MNE",
				numeric: 499,
			},
			{
				label: "Europe/Prague",
				value: "Europe/Prague",
				name: "Czechia",
				alpha2: "CZ",
				alpha3: "CZE",
				numeric: 203,
			},
			{
				label: "Europe/Riga",
				value: "Europe/Riga",
				name: "Latvia",
				alpha2: "LV",
				alpha3: "LVA",
				numeric: 428,
			},
			{
				label: "Europe/Rome",
				value: "Europe/Rome",
				name: "Italy",
				alpha2: "IT",
				alpha3: "ITA",
				numeric: 380,
			},
			{
				label: "Europe/Samara",
				value: "Europe/Samara",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/San_Marino",
				value: "Europe/San_Marino",
				name: "San Marino",
				alpha2: "SM",
				alpha3: "SMR",
				numeric: 674,
			},
			{
				label: "Europe/Sarajevo",
				value: "Europe/Sarajevo",
				name: "Bosnia and Herzegovina",
				alpha2: "BA",
				alpha3: "BIH",
				numeric: 70,
			},
			{
				label: "Europe/Saratov",
				value: "Europe/Saratov",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Simferopol",
				value: "Europe/Simferopol",
				name: "Ukraine",
				alpha2: "UA",
				alpha3: "UKR",
				numeric: 804,
			},
			{
				label: "Europe/Skopje",
				value: "Europe/Skopje",
				name: "Republic of North Macedonia",
				alpha2: "MK",
				alpha3: "MKD",
				numeric: 807,
			},
			{
				label: "Europe/Sofia",
				value: "Europe/Sofia",
				name: "Bulgaria",
				alpha2: "BG",
				alpha3: "BGR",
				numeric: 100,
			},
			{
				label: "Europe/Stockholm",
				value: "Europe/Stockholm",
				name: "Sweden",
				alpha2: "SE",
				alpha3: "SWE",
				numeric: 752,
			},
			{
				label: "Europe/Tallinn",
				value: "Europe/Tallinn",
				name: "Estonia",
				alpha2: "EE",
				alpha3: "EST",
				numeric: 233,
			},
			{
				label: "Europe/Tirane",
				value: "Europe/Tirane",
				name: "Albania",
				alpha2: "AL",
				alpha3: "ALB",
				numeric: 8,
			},
			{
				label: "Europe/Ulyanovsk",
				value: "Europe/Ulyanovsk",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Vaduz",
				value: "Europe/Vaduz",
				name: "Liechtenstein",
				alpha2: "LI",
				alpha3: "LIE",
				numeric: 438,
			},
			{
				label: "Europe/Vatican",
				value: "Europe/Vatican",
				name: "Holy See (the)",
				alpha2: "VA",
				alpha3: "VAT",
				numeric: 336,
			},
			{
				label: "Europe/Vienna",
				value: "Europe/Vienna",
				name: "Austria",
				alpha2: "AT",
				alpha3: "AUT",
				numeric: 40,
			},
			{
				label: "Europe/Vilnius",
				value: "Europe/Vilnius",
				name: "Lithuania",
				alpha2: "LT",
				alpha3: "LTU",
				numeric: 440,
			},
			{
				label: "Europe/Volgograd",
				value: "Europe/Volgograd",
				name: "Russian Federation (the)",
				alpha2: "RU",
				alpha3: "RUS",
				numeric: 643,
			},
			{
				label: "Europe/Warsaw",
				value: "Europe/Warsaw",
				name: "Poland",
				alpha2: "PL",
				alpha3: "POL",
				numeric: 616,
			},
			{
				label: "Europe/Zagreb",
				value: "Europe/Zagreb",
				name: "Croatia",
				alpha2: "HR",
				alpha3: "HRV",
				numeric: 191,
			},
			{
				label: "Europe/Zurich",
				value: "Europe/Zurich",
				name: "Switzerland",
				alpha2: "CH",
				alpha3: "CHE",
				numeric: 756,
			},
		],
	},
	{
		label: "Indian",
		options: [
			{
				label: "Indian/Antananarivo",
				value: "Indian/Antananarivo",
				name: "Madagascar",
				alpha2: "MG",
				alpha3: "MDG",
				numeric: 450,
			},
			{
				label: "Indian/Chagos",
				value: "Indian/Chagos",
				name: "British Indian Ocean Territory (the)",
				alpha2: "IO",
				alpha3: "IOT",
				numeric: 86,
			},
			{
				label: "Indian/Christmas",
				value: "Indian/Christmas",
				name: "Christmas Island",
				alpha2: "CX",
				alpha3: "CXR",
				numeric: 162,
			},
			{
				label: "Indian/Cocos",
				value: "Indian/Cocos",
				name: "Cocos (Keeling) Islands (the)",
				alpha2: "CC",
				alpha3: "CCK",
				numeric: 166,
			},
			{
				label: "Indian/Comoro",
				value: "Indian/Comoro",
				name: "Comoros (the)",
				alpha2: "KM",
				alpha3: "COM",
				numeric: 174,
			},
			{
				label: "Indian/Kerguelen",
				value: "Indian/Kerguelen",
				name: "French Southern Territories (the)",
				alpha2: "TF",
				alpha3: "ATF",
				numeric: 260,
			},
			{
				label: "Indian/Mahe",
				value: "Indian/Mahe",
				name: "Seychelles",
				alpha2: "SC",
				alpha3: "SYC",
				numeric: 690,
			},
			{
				label: "Indian/Maldives",
				value: "Indian/Maldives",
				name: "Maldives",
				alpha2: "MV",
				alpha3: "MDV",
				numeric: 462,
			},
			{
				label: "Indian/Mauritius",
				value: "Indian/Mauritius",
				name: "Mauritius",
				alpha2: "MU",
				alpha3: "MUS",
				numeric: 480,
			},
			{
				label: "Indian/Mayotte",
				value: "Indian/Mayotte",
				name: "Mayotte",
				alpha2: "YT",
				alpha3: "MYT",
				numeric: 175,
			},
			{
				label: "Indian/Reunion",
				value: "Indian/Reunion",
				name: "Réunion",
				alpha2: "RE",
				alpha3: "REU",
				numeric: 638,
			},
		],
	},
	{
		label: "Pacific",
		options: [
			{
				label: "Pacific/Apia",
				value: "Pacific/Apia",
				name: "Samoa",
				alpha2: "WS",
				alpha3: "WSM",
				numeric: 882,
			},
			{
				label: "Pacific/Auckland",
				value: "Pacific/Auckland",
				name: "New Zealand",
				alpha2: "NZ",
				alpha3: "NZL",
				numeric: 554,
			},
			{
				label: "Pacific/Bougainville",
				value: "Pacific/Bougainville",
				name: "Papua New Guinea",
				alpha2: "PG",
				alpha3: "PNG",
				numeric: 598,
			},
			{
				label: "Pacific/Chatham",
				value: "Pacific/Chatham",
				name: "New Zealand",
				alpha2: "NZ",
				alpha3: "NZL",
				numeric: 554,
			},
			{
				label: "Pacific/Chuuk",
				value: "Pacific/Chuuk",
				name: "Micronesia (Federated States of)",
				alpha2: "FM",
				alpha3: "FSM",
				numeric: 583,
			},
			{
				label: "Pacific/Easter",
				value: "Pacific/Easter",
				name: "Chile",
				alpha2: "CL",
				alpha3: "CHL",
				numeric: 152,
			},
			{
				label: "Pacific/Efate",
				value: "Pacific/Efate",
				name: "Vanuatu",
				alpha2: "VU",
				alpha3: "VUT",
				numeric: 548,
			},
			{
				label: "Pacific/Fakaofo",
				value: "Pacific/Fakaofo",
				name: "Tokelau",
				alpha2: "TK",
				alpha3: "TKL",
				numeric: 772,
			},
			{
				label: "Pacific/Fiji",
				value: "Pacific/Fiji",
				name: "Fiji",
				alpha2: "FJ",
				alpha3: "FJI",
				numeric: 242,
			},
			{
				label: "Pacific/Funafuti",
				value: "Pacific/Funafuti",
				name: "Tuvalu",
				alpha2: "TV",
				alpha3: "TUV",
				numeric: 798,
			},
			{
				label: "Pacific/Galapagos",
				value: "Pacific/Galapagos",
				name: "Ecuador",
				alpha2: "EC",
				alpha3: "ECU",
				numeric: 218,
			},
			{
				label: "Pacific/Gambier",
				value: "Pacific/Gambier",
				name: "French Polynesia",
				alpha2: "PF",
				alpha3: "PYF",
				numeric: 258,
			},
			{
				label: "Pacific/Guadalcanal",
				value: "Pacific/Guadalcanal",
				name: "Solomon Islands",
				alpha2: "SB",
				alpha3: "SLB",
				numeric: 90,
			},
			{
				label: "Pacific/Guam",
				value: "Pacific/Guam",
				name: "Guam",
				alpha2: "GU",
				alpha3: "GUM",
				numeric: 316,
			},
			{
				label: "Pacific/Honolulu",
				value: "Pacific/Honolulu",
				name: "United States of America (the)",
				alpha2: "US",
				alpha3: "USA",
				numeric: 840,
			},
			{
				label: "Pacific/Kanton",
				value: "Pacific/Kanton",
				name: "Kiribati",
				alpha2: "KI",
				alpha3: "KIR",
				numeric: 296,
			},
			{
				label: "Pacific/Kiritimati",
				value: "Pacific/Kiritimati",
				name: "Kiribati",
				alpha2: "KI",
				alpha3: "KIR",
				numeric: 296,
			},
			{
				label: "Pacific/Kosrae",
				value: "Pacific/Kosrae",
				name: "Micronesia (Federated States of)",
				alpha2: "FM",
				alpha3: "FSM",
				numeric: 583,
			},
			{
				label: "Pacific/Kwajalein",
				value: "Pacific/Kwajalein",
				name: "Marshall Islands (the)",
				alpha2: "MH",
				alpha3: "MHL",
				numeric: 584,
			},
			{
				label: "Pacific/Majuro",
				value: "Pacific/Majuro",
				name: "Marshall Islands (the)",
				alpha2: "MH",
				alpha3: "MHL",
				numeric: 584,
			},
			{
				label: "Pacific/Marquesas",
				value: "Pacific/Marquesas",
				name: "French Polynesia",
				alpha2: "PF",
				alpha3: "PYF",
				numeric: 258,
			},
			{
				label: "Pacific/Midway",
				value: "Pacific/Midway",
				name: "United States Minor Outlying Islands (the)",
				alpha2: "UM",
				alpha3: "UMI",
				numeric: 581,
			},
			{
				label: "Pacific/Nauru",
				value: "Pacific/Nauru",
				name: "Nauru",
				alpha2: "NR",
				alpha3: "NRU",
				numeric: 520,
			},
			{
				label: "Pacific/Niue",
				value: "Pacific/Niue",
				name: "Niue",
				alpha2: "NU",
				alpha3: "NIU",
				numeric: 570,
			},
			{
				label: "Pacific/Norfolk",
				value: "Pacific/Norfolk",
				name: "Norfolk Island",
				alpha2: "NF",
				alpha3: "NFK",
				numeric: 574,
			},
			{
				label: "Pacific/Noumea",
				value: "Pacific/Noumea",
				name: "New Caledonia",
				alpha2: "NC",
				alpha3: "NCL",
				numeric: 540,
			},
			{
				label: "Pacific/Pago_Pago",
				value: "Pacific/Pago_Pago",
				name: "American Samoa",
				alpha2: "AS",
				alpha3: "ASM",
				numeric: 16,
			},
			{
				label: "Pacific/Palau",
				value: "Pacific/Palau",
				name: "Palau",
				alpha2: "PW",
				alpha3: "PLW",
				numeric: 585,
			},
			{
				label: "Pacific/Pitcairn",
				value: "Pacific/Pitcairn",
				name: "Pitcairn",
				alpha2: "PN",
				alpha3: "PCN",
				numeric: 612,
			},
			{
				label: "Pacific/Pohnpei",
				value: "Pacific/Pohnpei",
				name: "Micronesia (Federated States of)",
				alpha2: "FM",
				alpha3: "FSM",
				numeric: 583,
			},
			{
				label: "Pacific/Port_Moresby",
				value: "Pacific/Port_Moresby",
				name: "Papua New Guinea",
				alpha2: "PG",
				alpha3: "PNG",
				numeric: 598,
			},
			{
				label: "Pacific/Rarotonga",
				value: "Pacific/Rarotonga",
				name: "Cook Islands (the)",
				alpha2: "CK",
				alpha3: "COK",
				numeric: 184,
			},
			{
				label: "Pacific/Saipan",
				value: "Pacific/Saipan",
				name: "Northern Mariana Islands (the)",
				alpha2: "MP",
				alpha3: "MNP",
				numeric: 580,
			},
			{
				label: "Pacific/Tahiti",
				value: "Pacific/Tahiti",
				name: "French Polynesia",
				alpha2: "PF",
				alpha3: "PYF",
				numeric: 258,
			},
			{
				label: "Pacific/Tarawa",
				value: "Pacific/Tarawa",
				name: "Kiribati",
				alpha2: "KI",
				alpha3: "KIR",
				numeric: 296,
			},
			{
				label: "Pacific/Tongatapu",
				value: "Pacific/Tongatapu",
				name: "Tonga",
				alpha2: "TO",
				alpha3: "TON",
				numeric: 776,
			},
			{
				label: "Pacific/Wake",
				value: "Pacific/Wake",
				name: "United States Minor Outlying Islands (the)",
				alpha2: "UM",
				alpha3: "UMI",
				numeric: 581,
			},
			{
				label: "Pacific/Wallis",
				value: "Pacific/Wallis",
				name: "Wallis and Futuna",
				alpha2: "WF",
				alpha3: "WLF",
				numeric: 876,
			},
		],
	},
]

export default TIME_ZONES
